config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  root "reviews#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord

  validates :title, presence: true
  validates :body, length: { minimum: 10 }
  validates :score, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :restaurant, presence: true

  def to_param
    id.to_s + "-" + title.parameterize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    # this is our list page for our reviews

    @number = rand(100)

    @reviews = Review.all

  end

  def new
    # the form for adding a new review
    @review = Review.new
  end

  def create
    # take info from form and add to database
    @review = Review.new(form_params)

    # we want to check if the model can be saved
    # if it is, we're going to the homepage again
    # if it isn't, show the new form
    if @review.save
      redirect_to root_path
    else
      # show the view for new.html.erb
      render "new"
    end

  end

  def show
    # individual review page
    @review = Review.find(params[:id])
  end

  def destroy
    # find individual review
    @review = Review.find(params[:id])

    # destroy
    @review.destroy

    #redirect to homepage
    redirect_to root_path
  end

  def edit
    # find individual review to edit
    @review = Review.find(params[:id])
  end

  def update
    # find individual review
    @review = Review.find(params[:id])

    # update with new info
    if @review.update(form_params)

      # redirect to somewhere new
      redirect_to review_path(@review)
    else
      render "edit"
    end
  end

  def form_params
    params.require(:review).permit(:title, :restaurant, :body, :score, :ambiance)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for :page_title %> - Bien Reviews - The best restaurants in the world</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
          <h1><%= link_to root_path  do %>
            <%= image_tag "bien-logo.svg" %>
          <% end %>
          </h1>
      </nav>

      <nav>
        <%= link_to "Add a review", new_review_path %>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      Copyright 2017 Bien Reviews
    </footer>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>

  <% if @review.errors.any? %>

    <div class="errors">

      <% @review.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>

    </div>

  <% end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :restaurant %>
    <%= f.text_field :restaurant %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.label :score %>
    <%= f.number_field :score %>
  </p>

  <p>
    <%= f.label :ambiance %>
    <%= f.text_field :ambiance %>
  </p>

  <%= f.submit "Save review" %>

<% end %>

app/views/reviews/edit.html.erb
<% content_for :page_title, "Edit your restaurant review" %>

<h3>Edit your restaurant review!</h3>

<%= render "form" %>

app/views/reviews/index.html.erb
<% @reviews.each do |review| %>

  <div class="review">
    <%= link_to review.title, review_path(review) %>
  </div>

<% end %>

app/views/reviews/new.html.erb
<% content_for :page_title, "Add a new review" %>

<h3>Add your new restaurant review!</h3>

<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for :page_title, @review.title %>

<h1><%= @review.title %></h1>
<h2><%= @review.restaurant %></h2>

<div class="score">
  <%= @review.score %> / 10
</div>

<% if @review.ambiance.present? %>
  <div class="ambiance">
    Ambiance: <%= @review.ambiance %>
  </div>
<% end %>

<div class="body">
  <%= simple_format @review.body %>
</div>

<div class="actions">
  <%= link_to "Edit this review", edit_review_path(@review) %>
  <%= link_to "Delete this review", review_path(@review), method: :delete, data: { confirm: "Are you sure?" } %>
</div>